import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { parse, stringify } from 'yaml';
import type { Schema, Table, Column } from '../types/index.js';

export function validateIdentifier(name: string, type: string): string {
  if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(name)) {
    throw new Error(`Invalid ${type} name: "${name}". Only letters, numbers, and underscores allowed.`);
  }
  return name;
}

export function parseSchema(yamlContent: string): Schema {
  const parsed = parse(yamlContent);

  if (!parsed || !Array.isArray(parsed.tables)) {
    throw new Error('Invalid schema: must contain a "tables" array');
  }

  const tables: Table[] = parsed.tables.map((table: Record<string, unknown>) => {
    if (!table.name || !Array.isArray(table.columns)) {
      throw new Error(`Invalid table definition: each table must have "name" and "columns"`);
    }

    const columns: Column[] = (table.columns as Record<string, unknown>[]).map((col) => {
      if (!col.name || typeof col.name !== 'string') {
        throw new Error(`Invalid column in table "${table.name}": missing or invalid "name"`);
      }
      if (!col.type || typeof col.type !== 'string') {
        throw new Error(`Invalid column "${col.name}" in table "${table.name}": missing or invalid "type"`);
      }

      return {
        name: col.name as string,
        type: col.type as string,
        primary: col.primary as boolean | undefined,
        unique: col.unique as boolean | undefined,
        nullable: col.nullable as boolean | undefined,
        default: col.default as string | undefined,
        references: col.references as string | undefined,
      };
    });

    return { name: table.name as string, columns };
  });

  return { tables };
}

export function loadSchema(filePath: string): Schema {
  if (!existsSync(filePath)) {
    throw new Error(`Schema file not found: ${filePath}`);
  }
  const content = readFileSync(filePath, 'utf-8');
  return parseSchema(content);
}

export function saveSchema(schema: Schema, filePath: string): void {
  const yamlContent = stringify(schema, { lineWidth: 120 });
  writeFileSync(filePath, yamlContent);
}

export function schemaToSQL(schema: Schema): string {
  const statements: string[] = [];

  for (const table of schema.tables) {
    validateIdentifier(table.name, 'table');
    const columnDefs: string[] = [];

    for (const col of table.columns) {
      validateIdentifier(col.name, 'column');
      const parts: string[] = [col.name, mapColumnType(col.type)];

      if (col.primary) parts.push('PRIMARY KEY');
      if (col.unique) parts.push('UNIQUE');
      if (!col.nullable && !col.primary) parts.push('NOT NULL');
      if (col.default) parts.push(`DEFAULT ${col.default}`);

      columnDefs.push(`  ${parts.join(' ')}`);
    }

    // Add foreign key constraints
    for (const col of table.columns) {
      if (col.references) {
        const parts = col.references.split('.');
        if (parts.length !== 2 || !parts[0] || !parts[1]) {
          throw new Error(`Invalid reference "${col.references}" in column "${col.name}". Expected format: table.column`);
        }
        const [refTable, refColumn] = parts;
        validateIdentifier(refTable, 'reference table');
        validateIdentifier(refColumn, 'reference column');
        columnDefs.push(`  FOREIGN KEY (${col.name}) REFERENCES ${refTable}(${refColumn})`);
      }
    }

    statements.push(
      `CREATE TABLE IF NOT EXISTS ${table.name} (\n${columnDefs.join(',\n')}\n);`
    );
  }

  return statements.join('\n\n');
}

function mapColumnType(type: string): string {
  const typeMap: Record<string, string> = {
    uuid: 'UUID',
    string: 'VARCHAR(255)',
    text: 'TEXT',
    integer: 'INTEGER',
    int: 'INTEGER',
    float: 'FLOAT',
    decimal: 'DECIMAL',
    boolean: 'BOOLEAN',
    timestamp: 'TIMESTAMP',
    date: 'DATE',
    json: 'JSONB',
    jsonb: 'JSONB',
  };

  return typeMap[type.toLowerCase()] || type.toUpperCase();
}

export function generateMigration(schema: Schema): string {
  const timestamp = new Date().toISOString().replace(/[^0-9]/g, '').slice(0, 14);
  const sql = schemaToSQL(schema);

  return `-- Migration: ${timestamp}\n-- Generated by BackForge\n\n${sql}\n`;
}

export function createEmptySchema(): Schema {
  return { tables: [] };
}

export function addTable(schema: Schema, table: Table): Schema {
  return {
    ...schema,
    tables: [...schema.tables, table],
  };
}

export function removeTable(schema: Schema, tableName: string): Schema {
  return {
    ...schema,
    tables: schema.tables.filter((t) => t.name !== tableName),
  };
}
