import type { Schema, Column } from '../types/index.js';

export function generateTypes(schema: Schema): string {
  const lines: string[] = [
    '// Generated by BackForge — do not edit manually',
    `// Generated at: ${new Date().toISOString()}`,
    '',
  ];

  for (const table of schema.tables) {
    const interfaceName = toPascalCase(table.name);
    lines.push(`export interface ${interfaceName} {`);

    for (const col of table.columns) {
      const tsType = mapToTsType(col);
      const optional = col.nullable ? '?' : '';
      lines.push(`  ${col.name}${optional}: ${tsType};`);
    }

    lines.push('}');
    lines.push('');
  }

  // Generate insert types (omit auto-generated fields)
  for (const table of schema.tables) {
    const interfaceName = toPascalCase(table.name);
    const insertFields = table.columns.filter(
      (col) => !col.primary && !col.default
    );

    if (insertFields.length > 0) {
      lines.push(`export interface ${interfaceName}Insert {`);
      for (const col of insertFields) {
        const tsType = mapToTsType(col);
        const optional = col.nullable ? '?' : '';
        lines.push(`  ${col.name}${optional}: ${tsType};`);
      }
      lines.push('}');
      lines.push('');
    }
  }

  // Generate update types (all fields optional)
  for (const table of schema.tables) {
    const interfaceName = toPascalCase(table.name);
    const updateFields = table.columns.filter((col) => !col.primary);

    if (updateFields.length > 0) {
      lines.push(`export interface ${interfaceName}Update {`);
      for (const col of updateFields) {
        const tsType = mapToTsType(col);
        lines.push(`  ${col.name}?: ${tsType};`);
      }
      lines.push('}');
      lines.push('');
    }
  }

  return lines.join('\n');
}

function mapToTsType(col: Column): string {
  const typeMap: Record<string, string> = {
    uuid: 'string',
    string: 'string',
    text: 'string',
    integer: 'number',
    int: 'number',
    float: 'number',
    decimal: 'number',
    boolean: 'boolean',
    timestamp: 'Date',
    date: 'Date',
    json: 'Record<string, unknown>',
    jsonb: 'Record<string, unknown>',
  };

  return typeMap[col.type.toLowerCase()] || 'unknown';
}

function toPascalCase(str: string): string {
  return str
    .split(/[_\-\s]+/)
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
    .join('');
}
